<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="12" total="16" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-12T20:29:49 IST" name="Regression" finished-at="2022-09-12T20:29:49 IST" duration-ms="68">
    <groups>
      <group name="Regression">
        <method signature="HealthInsurance.HealthWebLogin()[pri:1, instance:Insurance.HealthInsurance@294425a7]" name="HealthWebLogin" class="Insurance.HealthInsurance"/>
        <method signature="HomeInsurance.HomeWebLogin()[pri:1, instance:Insurance.HomeInsurance@2a798d51]" name="HomeWebLogin" class="Insurance.HomeInsurance"/>
        <method signature="LifeInsurance.LifeWebLogin()[pri:1, instance:Insurance.LifeInsurance@6d763516]" name="LifeWebLogin" class="Insurance.LifeInsurance"/>
        <method signature="VehicleInsurance.VehicleWebLogin()[pri:1, instance:Insurance.VehicleInsurance@52bf72b5]" name="VehicleWebLogin" class="Insurance.VehicleInsurance"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2022-09-12T20:29:49 IST" name="Test" finished-at="2022-09-12T20:29:49 IST" duration-ms="68">
      <class name="Insurance.HomeInsurance">
        <test-method signature="HomeWebLogin()[pri:1, instance:Insurance.HomeInsurance@2a798d51]" started-at="2022-09-12T20:29:49 IST" name="HomeWebLogin" finished-at="2022-09-12T20:29:49 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomeWebLogin -->
      </class> <!-- Insurance.HomeInsurance -->
      <class name="Insurance.LifeInsurance">
        <test-method signature="LifeWebLogin()[pri:1, instance:Insurance.LifeInsurance@6d763516]" started-at="2022-09-12T20:29:49 IST" name="LifeWebLogin" finished-at="2022-09-12T20:29:49 IST" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at Insurance.LifeInsurance.LifeWebLogin(LifeInsurance.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LifeWebLogin -->
      </class> <!-- Insurance.LifeInsurance -->
      <class name="Insurance.HealthInsurance">
        <test-method signature="HealthWebLogin()[pri:1, instance:Insurance.HealthInsurance@294425a7]" started-at="2022-09-12T20:29:49 IST" name="HealthWebLogin" finished-at="2022-09-12T20:29:49 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HealthWebLogin -->
      </class> <!-- Insurance.HealthInsurance -->
      <class name="Insurance.VehicleInsurance">
        <test-method signature="VehicleWebLogin()[pri:1, instance:Insurance.VehicleInsurance@52bf72b5]" started-at="2022-09-12T20:29:49 IST" name="VehicleWebLogin" finished-at="2022-09-12T20:29:49 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VehicleWebLogin -->
      </class> <!-- Insurance.VehicleInsurance -->
    </test> <!-- Test -->
  </suite> <!-- Regression -->
</testng-results>
