<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-19T20:35:54 IST" name="Suite" finished-at="2022-10-19T20:35:59 IST" duration-ms="5031">
    <groups>
    </groups>
    <test started-at="2022-10-19T20:35:54 IST" name="Test" finished-at="2022-10-19T20:35:59 IST" duration-ms="5031">
      <class name="com.RegressionTestCases.VerifyUserLoginTest">
        <test-method is-config="true" signature="logcall()[pri:0, instance:com.RegressionTestCases.VerifyUserLoginTest@409bf450]" started-at="2022-10-19T20:35:53 IST" name="logcall" finished-at="2022-10-19T20:35:54 IST" duration-ms="234" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logcall -->
        <test-method is-config="true" signature="beforesuit()[pri:0, instance:com.RegressionTestCases.VerifyUserLoginTest@409bf450]" started-at="2022-10-19T20:35:54 IST" name="beforesuit" finished-at="2022-10-19T20:35:54 IST" depends-on-methods="com.BaseClass.BaseClass.logcall" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforesuit -->
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:com.RegressionTestCases.VerifyUserLoginTest@409bf450]" started-at="2022-10-19T20:35:54 IST" name="loadConfig" finished-at="2022-10-19T20:35:54 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method is-config="true" signature="call()[pri:0, instance:com.RegressionTestCases.VerifyUserLoginTest@409bf450]" started-at="2022-10-19T20:35:54 IST" name="call" finished-at="2022-10-19T20:35:58 IST" depends-on-methods="com.BaseClass.BaseClass.loadConfig" duration-ms="4668" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- call -->
        <test-method signature="ValidUserLoginTest()[pri:0, instance:com.RegressionTestCases.VerifyUserLoginTest@409bf450]" started-at="2022-10-19T20:35:58 IST" name="ValidUserLoginTest" finished-at="2022-10-19T20:35:59 IST" duration-ms="326" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at com.RegressionTestCases.VerifyUserLoginTest.ValidUserLoginTest(VerifyUserLoginTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidUserLoginTest -->
        <test-method is-config="true" signature="end()[pri:0, instance:com.RegressionTestCases.VerifyUserLoginTest@409bf450]" started-at="2022-10-19T20:35:59 IST" name="end" finished-at="2022-10-19T20:36:15 IST" duration-ms="16248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- com.RegressionTestCases.VerifyUserLoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
